# Coding Quiz #1

## 1부터 100 사이의 홀수와 짝수의 누적합을 구하시오. (10점)

In [ ]:
even_sum = 0
odd_sum = 0

for i in range(1, 101):
  if i % 2 == 0:
    even_sum += i
  else:
    odd_sum += i
else:
  print('짝수 합 =',even_sum, ', 홀수 합 = ',odd_sum)

짝수 합 = 2550 , 홀수 합 =  2500

## 2부터 100 사이의 소수를 구하는 코드를 작성하시오. (30점)

In [ ]:
for i in range(2, 101):
  if i == 2:
    print(i)
  for j in range(2, i):
    if i % j == 0:
      break
    elif i-1 == j:
      print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97

## 가장 짧은 도시 이름을 출력하는 코드를 작성하시오. (30점)

In [116]:
cities = ['daejeon', 'seoul', 'daegu', 'busan', 'chuncheon', 'uijeongbu']

shortest = cities[0]


for s in cities:            #글자 수가 가장 작은 도시 이름을 찾는 과정
  if len(shortest) > len(s):
    shortest = s

cities_2 = []

for s in cities:            #글자 수가 가장 작은 도시들을 리스트에 넣는 과정
  if len(shortest) == len(s):
    shortest = s
    cities_2.append(shortest)
else:
  print(cities_2)

['seoul', 'daegu', 'busan']

## 나이에 따른 입장료를 계산하는 코드를 작성하시오. (30점)

* 1~7세: 1000원
* 8~20세: 2000원
* 21~40세: 3000원
* 41~세: 1500원

In [ ]:
age = 30
pay = 0

if age <= 0:
  print("나이를 다시 입력하세요")
elif age <= 20:
  pay = 2000
elif age <= 40:
  pay = 3000
else:
  pay = 1500 


print("나이: {0}, 입장료: {1}".format(age, pay))

나이: 30, 입장료: 3000